theme: jekyll-theme-cayman
title: "SFAD: Selective and Features based Adversarial Detection"
description: "ALDAHDOOH Ahmed, HAMIDOUCHE Wassim, DEFORGES Olivier|Univ Rennes, INSA Rennes, CNRS, IETR - UMR 6164, F-35000 Rennes, France|SFAD is an unsupervised Adversarial Examples (AEs) detector"
show_downloads: false
