theme: jekyll-theme-cayman
title: "SFAD: Selective and Features based Adversarial Detection"
description: |+ 
    "ALDAHDOOH Ahmed, HAMIDOUCHE Wassim, DEFORGES Olivier\n" 
    "Univ Rennes, INSA Rennes, CNRS, IETR - UMR 6164, F-35000 Rennes, France\n" 
    \n
    \n
    "SFAD is an unsupervised Adversarial Examples (AEs) detector\n"
    \n
show_downloads: false
